version: '2'
services:
  app:
    build: ./app
    expose:
      - "80"
  
  gui:
    build: ./wpe
    depends_on:
      - app
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/fb1:/dev/fb1"
      - "/dev/vchiq:/dev/vchiq"
